name: automated-testing-integration

on:
  push:
    branches: [ "ae-micros-valentin" ]
  pull_request:
    branches: [ "ae-micros-valentin" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  sonar:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - name: Checking Sonar Action
        uses: actions/checkout@v2
        with:
          repository: bancodebogota/bbog-dig-sonarcloud-pipeline
          ref: ''
          token: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/bbog-dig-sonarcloud-pipeline
      - name: Restore Data
        uses: actions/download-artifact@v2
        with:
          name: target
          path: target/
      - name: Current Branch
        shell: bash
        run: |
          CURRENT_BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          MASTER_BRANCH_REGEX="^(master|release)$"
          STAGING_BRANCH_REGEX="^(stage|staging|HOTFIX_.+)$"
          if [[ $CURRENT_BRANCH =~ $STAGING_BRANCH_REGEX ]]
          then
              CURRENT_BRANCH="staging"
          elif [[ ! $CURRENT_BRANCH =~ $MASTER_BRANCH_REGEX ]]
          then
              CURRENT_BRANCH="qa"
          fi
          echo "Sonar Branch report => " ${CURRENT_BRANCH}
          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV
        id: long-lived-branch
      - name: SonarCloud Scanner
        uses: ./.github/actions/bbog-dig-sonarcloud-pipeline
        with:
          language: ${{ env.language }}
          current-branch: ${CURRENT_BRANCH}
          access-token: ${{ secrets.SONAR_CLOUD_TOKEN }}
          project-name: bbog-${{ env.team }}-${{ env.project-name }}
          project-key: bbog-${{ env.team }}-${{ env.project-name }}
          sonar-project-properties-file: sonar-project-custom.properties